services:
  db:
    image: postgres:18
    container_name: student-intervention-db
    environment:
      POSTGRES_DB: credit_recovery
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - "5433:5432"

  web:
    build: .
    container_name: student-intervention-container
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    depends_on:
      - db

volumes:
  postgres_data: